services:
  app:
    depends_on:
      postgres:
        condition: service_healthy
    image: ghcr.io/olli107x/morningcrunch-sign:latest
    ports:
      - 3000:3000
    volumes:
      - ./data:/data/morningcrunch-sign
    environment:
      - HOST=${HOST:-localhost}
      - FORCE_SSL=${FORCE_SSL:-true}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD:-postgres}@postgres:5432/morningcrunch_sign

  postgres:
    image: postgres:17
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: morningcrunch_sign
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  caddy:
    image: caddy:latest
    command: caddy reverse-proxy --from ${HOST:-localhost} --to app:3000
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./caddy_data:/data
    environment:
      - HOST=${HOST:-localhost}
